services:
  mariadb:
    image: mariadb:10.7.1
    env_file:
      - .env
    volumes:
      - beerdb:/var/lib/mysql
    ports:
      - 3307:3306
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 9999:8080

volumes:
  beerdb: