services:
  mariadb:
    image: mariadb:10.5.12
    ports:
      - 3307:3306
    env_file:
      - .env
    volumes:
      - poopvolume:/var/lib/mysql
    

  adminer:
    image: adminer:4.8.1
    ports:
      - 9999:8080

volumes:
  poopvolume: